config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, shallow: true, except: %i[show] do
    resources :clients, only: %i[index]
    resources :employees, except: %i[show] do
      resources :clients, except: %i[show]
    end
  end

  root to: 'companies#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: clients
#
#  id          :integer          not null, primary key
#  first_name  :string
#  last_name   :string
#  ctoken      :string
#  employee_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Client < ApplicationRecord
  belongs_to :employee, counter_cache: true

  has_unique_identifier :ctoken,
                        segment_count: 3,
                        segment_size: 2,
                        delimiter: '-'

  delegate :full_name, to: :name

  private

  def name
    Name.new(first_name, last_name)
  end
end

app/models/company.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  identity   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
  has_many :clients, -> { distinct }, through: :employees

  has_unique_identifier :identity,
                        segment_count: 2,
                        segment_size: 4,
                        delimiter: ':'

  def clients_count
    employees.map(&:clients_count).reduce(0, :+)
  end
end

app/models/employee.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: employees
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  identifier :string
#  company_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Employee < ApplicationRecord
  belongs_to :company, counter_cache: true
  has_many :clients, dependent: :destroy

  has_unique_identifier :identifier,
                        segment_count: 3,
                        segment_size: 2,
                        delimiter: '-'

  delegate :full_name, to: :name

  def co_workers(include_self: false)
    include_self ? company.employees : company.employees - [self]
  end

  def allow_destroy?
    clients_count.zero?
  end

  private

  def name
    Name.new(first_name, last_name)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :set_client, only: %i[edit update destroy]

  def index
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @clients = @company.clients
      @employee = @company.employees.first
    else
      @employee = Employee.find(params[:employee_id])
      @company = @employee.company
      @clients = @employee.clients
    end
  end

  def new
    @employee = Employee.find(params[:employee_id])
    @client = @employee.clients.build
    @company_employees = @employee.co_workers(include_self: true)
  end

  def edit
    @employee = @client.employee
    @company_employees = @employee.co_workers(include_self: true)
  end

  def create
    @client = Client.new(client_params)
    @employee = @client.employee

    if @client.save
      # rubocop:disable Metrics/LineLength
      redirect_to employee_clients_path(@employee), notice: 'Client was successfully created.'
    # rubocop:enable Metrics/LineLength
    else
      render :new
    end
  end

  def update
    UpdatesClient.new(@client, client_params)
    # rubocop:disable Metrics/LineLength
    redirect_to employee_clients_path(@client.employee), notice: 'Client was successfully updated.'
    # rubocop:enable Metrics/LineLength
  end

  def destroy
    @client.destroy
    # rubocop:disable Metrics/LineLength
    redirect_to employee_clients_path(@client.employee), notice: 'Client was successfully destroyed.'
    # rubocop:enable Metrics/LineLength
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:first_name, :last_name, :employee_id)
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :set_company, only: %i[edit update destroy]

  def index
    @companies = Company.all.includes(:employees).order(:name)
  end

  def new
    @company = Company.new
  end

  def edit; end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to companies_path, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to companies_path, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[edit update destroy]
  before_action :set_company, except: %i[update destroy]

  def index
    @employees = @company.employees
  end

  def new
    @employee = @company.employees.build
    @companies = Company.all
  end

  def edit
    @companies = Company.all
  end

  def create
    @employee = @company.employees.build(employee_params)

    if @employee.save
      # rubocop:disable Metrics/LineLength
      redirect_to company_employees_path(@company), notice: 'Employee was successfully created.'
    # rubocop:enable Metrics/LineLength
    else
      render :new
    end
  end

  def update
    if @employee.update(employee_params)
      # rubocop:disable Metrics/LineLength
      redirect_to company_employees_path(@employee.company), notice: 'Employee was successfully updated.'
    # rubocop:enable Metrics/LineLength
    else
      render :edit
    end
  end

  def destroy
    # rubocop:disable Metrics/LineLength
    if @employee.allow_destroy?
      @employee.destroy
      redirect_to company_employees_path(@employee.company), notice: 'Employee was successfully destroyed.'
    else
      redirect_to company_employees_path(@employee.company), alert: 'Cannot destroy employee with assigned clients.'
    end
    # rubocop:enable Metrics/LineLength
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def set_company
    # rubocop:disable Metrics/LineLength
    @company = params[:company_id] ? Company.find(params[:company_id]) : @employee.company
    # rubocop:enable Metrics/LineLength
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :company_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def alert_class(alert_type)
    specific = case alert_type
               when 'notice' then 'alert alert-success'
               when 'alert' then 'alert alert-danger'
               else
                 'alert alert-primary'
               end
    "#{specific} alert-dismissible fade show"
  end
end

app/views/clients/_client.html.erb
<div id="client-<%= client.id %>" class="client card">
    <div class="card-body">
	<div class="row">
	    <div class="col-3 full-name">
		<strong>
		    <%= client.full_name %>
		</strong>
	    </div>
	    <div class="col-3 ctoken">
		Client Token: <%= client.ctoken %>
	    </div>
	    <div class="col-3 employee-full-name">
		<%= link_to "Employee: #{client.employee.full_name}", employee_clients_path(client.employee), class: "text-muted" %>
	    </div>
	    <div class="col-3">
		<div class="float-right">
		    <%= link_to 'Edit', edit_client_path(client), class: "btn btn-secondary btn-sm" %>
		    <%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
		</div>
	    </div>
	</div>
    </div>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true, url: (client.new_record? ? [@employee, client]: client), builder: BootstrapFormBuilder) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.group :first_name do %>
    <%= form.label :first_name, 'First Name' %>
    <%= form.text_field :first_name %>
  <% end %>

  <%= form.group :last_name do %>
    <%= form.label :last_name, 'Last Name' %>
    <%= form.text_field :last_name %>
  <% end %>

  <%= form.group :employee_id do %>
    <%= form.label :employee_id %>
    <%= form.select :employee_id, @company_employees.sort_by(&:full_name).map { |e| [e.full_name, e.id] } %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', employee_clients_path(@employee) %>

app/views/clients/index.html.erb
<div class="clearfix">
    <div class="float-right">
	<%= link_to 'New Client', new_employee_client_path(@employee), class: "btn btn-primary btn-sm m-2" %>
    </div>
</div>

<%= render partial: "client", collection: @clients.sort_by(&:full_name)  %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', employee_clients_path(@employee) %>

app/views/companies/_company.html.erb
<div id="company-<%= company.id %>" class="company card">
    <div class="card-body">
      <h5 class="card-title name"><%= company.name %></h5>
      <div class="row">
	  <div class="col-3 identity">
	      Identity: <%= company.identity %>
	  </div>
	  <div class="col-3 employee-count">
	      <%= link_to "Employee Count: #{company.employees_count}", company_employees_path(company), class: "text-muted" %>
	  </div>
	  <div class="col-3 client-count">
	      <%= link_to "Client Count: #{company.clients_count}", company_clients_path(company), class: "text-muted" %>
	  </div>
	  <div class="col-3">
	      <%= link_to 'Edit', edit_company_path(company), class: "btn btn-secondary btn-sm" %>
	      <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
	  </div>
      </div>
    </div>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true, builder: BootstrapFormBuilder) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.group :name do %>
    <%= form.label :name %>
    <%= form.text_field :name %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="float-right">
    <%= link_to 'New Company', new_company_path, class: "btn btn-primary btn-sm m-2" %>
</div>

<h1>Companies</h1>

<div class="companies">
    <%= render partial: "company", collection: @companies %>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/employees/_employee.html.erb
<div id="employee-<%= employee.id %>" class="employee card">
    <div class="card-body">
      <h5 class="card-title full-name"><%= employee.full_name %></h5>
      <div class="row">
	  <div class="col-4 identifier">
	      Identifier: <%= employee.identifier %>
	  </div>
	  <div class="col-4 client-count">
	      <%= link_to "Client Count: #{employee.clients_count}", employee_clients_path(employee), class: "text-muted" %>
	  </div>
	  <div class="col-4">
	      <%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-secondary btn-sm" %>
	      <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm #{'disabled' unless employee.allow_destroy?}" %>
	  </div>
      </div>
    </div>
</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true, url: (employee.new_record? ? [@company, employee]: employee), builder: BootstrapFormBuilder) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.group :name do %>
    <%= form.label :first_name, 'First Name' %>
    <%= form.text_field :first_name %>
  <% end %>

  <%= form.group :name do %>
    <%= form.label :last_name, 'Last Name' %>
    <%= form.text_field :last_name %>
  <% end %>

  <%= form.group :company_id do %>
    <%= form.label :company_id %>
    <%= form.select :company_id, @companies.sort_by(&:name).map { |c| [c.name, c.id] } %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', company_employees_path(@company) %>

app/views/employees/index.html.erb
<div class="clearfix">
    <div class="float-right">
	<%= link_to 'New Employee', new_company_employee_path(@company), class: "btn btn-primary btn-sm m-2" %>
    </div>
</div>

<%= render partial: "employee", collection: @employees.sort_by(&:full_name) %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', company_employees_path(@company) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
	<title>IdentifierToken</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="container">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	    <a class="navbar-brand" href="<%= root_path %>">
		<%= fa_icon "home" %>
	    </a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	    </button>

	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<% if @company && @company.persisted? %>
		    <ul class="navbar-nav mr-auto">
			<span class="navbar-text"><%= @company.name %></span>
			
			<% path = company_employees_path(@company) %>
			<li class="nav-item <%= 'active' if current_page?(path) %>">
			    <a class="nav-link" href="<%= path %>">Employees</a>
			</li>
			
			<% path = company_clients_path(@company) %>
			<li class="nav-item <%= 'active' if current_page?(path) %>">
			    <a class="nav-link" href="<%= path %>">Clients</a>
			</li>
		    </ul>
		<% end %>
	    </div>
	</nav>

	<% flash.each do |type, message| %>
	    <div class="<%= alert_class(type) %>">
		<%= message%>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		</button>
	    </div>
	<% end %>

	<%= yield %>
    </body>
</html>